import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
// import { headers } from "next/headers";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  route1,
  route2,
}: {
  children: React.ReactNode,
  route1: React.ReactNode,
  route2: React.ReactNode,
}) {

  // const origin = headers().get("host")
  const isRoute1 = true;

  let view: React.ReactNode;
  if (isRoute1) {
    view = route1;
  } else {
    view = route2;
  }
  return (
    <html lang="en">
      <body className={inter.className}>{view}</body>
    </html>
  )
}
